
# https://alacritty.org/config-alacritty.html
[shell]
args = ["--login", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
opacity = 0.85
startup_mode = "Windowed"
dynamic_padding = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11.50
normal.family = "CaskaydiaCove NF"
normal.style = "Regular"
bold.family = "CaskaydiaCove NF"
bold.style = "Bold"
italic.family = "CaskaydiaCove NF"
italic.style = "Italic"

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[bell]
duration = 5

[cursor]
style.shape = "Block"
style.blinking = "Off"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[debug]
# prefer_egl = true
# log_level = "Warn"
# persistent_logging = false
# print_events = false
# render_timer = false
